version: "3"

services:
  api:
    build: .
    restart: always
    depends_on:
      - mongo
    volumes:
      - ./:/home/node
      - /home/node/node_modules
  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  rproxy:
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
